from __future__ import annotations

DENY_MULTI_STATEMENT = "DENY_MULTI_STATEMENT"
DENY_UNSUPPORTED_SQL_SYNTAX = "DENY_UNSUPPORTED_SQL_SYNTAX"
DENY_RESOURCE_ABUSE = "DENY_RESOURCE_ABUSE"
DENY_EXTERNAL_DATA_ACCESS = "DENY_EXTERNAL_DATA_ACCESS"
DENY_LINKED_SERVER = "DENY_LINKED_SERVER"
DENY_DYNAMIC_SQL = "DENY_DYNAMIC_SQL"
DENY_PROCEDURE_EXECUTION = "DENY_PROCEDURE_EXECUTION"
DENY_WRITE_OPERATION = "DENY_WRITE_OPERATION"
DENY_TEMP_OBJECT = "DENY_TEMP_OBJECT"
DENY_DISALLOWED_HINT = "DENY_DISALLOWED_HINT"
DENY_SYSTEM_CATALOG_ACCESS = "DENY_SYSTEM_CATALOG_ACCESS"
DENY_CROSS_DATABASE = "DENY_CROSS_DATABASE"

DENY_SOURCE_BINDING_MISMATCH = "DENY_SOURCE_BINDING_MISMATCH"
DENY_UNSUPPORTED_SOURCE_BINDING = "DENY_UNSUPPORTED_SOURCE_BINDING"
DENY_SUBJECT_MISMATCH = "DENY_SUBJECT_MISMATCH"
DENY_APPROVAL_EXPIRED = "DENY_APPROVAL_EXPIRED"
DENY_CANDIDATE_INVALIDATED = "DENY_CANDIDATE_INVALIDATED"
DENY_POLICY_VERSION_STALE = "DENY_POLICY_VERSION_STALE"
DENY_ENTITLEMENT_CHANGED = "DENY_ENTITLEMENT_CHANGED"
DENY_APPLICATION_POSTGRES_REUSE = "DENY_APPLICATION_POSTGRES_REUSE"

GUARD_DENY_CODES = frozenset(
    {
        DENY_MULTI_STATEMENT,
        DENY_UNSUPPORTED_SQL_SYNTAX,
        DENY_RESOURCE_ABUSE,
        DENY_EXTERNAL_DATA_ACCESS,
        DENY_LINKED_SERVER,
        DENY_DYNAMIC_SQL,
        DENY_PROCEDURE_EXECUTION,
        DENY_WRITE_OPERATION,
        DENY_TEMP_OBJECT,
        DENY_DISALLOWED_HINT,
        DENY_SYSTEM_CATALOG_ACCESS,
        DENY_CROSS_DATABASE,
    }
)

EXECUTION_DENY_CODES = frozenset(
    {
        DENY_SOURCE_BINDING_MISMATCH,
        DENY_UNSUPPORTED_SOURCE_BINDING,
        DENY_SUBJECT_MISMATCH,
        DENY_APPROVAL_EXPIRED,
        DENY_CANDIDATE_INVALIDATED,
        DENY_POLICY_VERSION_STALE,
        DENY_ENTITLEMENT_CHANGED,
        DENY_APPLICATION_POSTGRES_REUSE,
    }
)

SHARED_DENY_CODES = GUARD_DENY_CODES | EXECUTION_DENY_CODES
